---
apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: local-mantannest-com
  namespace: traefik

spec:
  secretName: local-mantannest-com-tls

  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

  commonName: "*.local.mantannest.com"

  dnsNames:
    - "local.mantannest.com"
    - "*.local.mantannest.com"
