---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../secrets/oci-production/discord-webhook.enc.yaml"
  - "../base/flux-system/alert-discord/"
  - "../../secrets/oci-production/githubtoken.enc.yaml"
  - "../base/flux-system/alert-github/"
  - "../base/kube-system/"
  - "../base/networking/"

patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: traefik
      namespace: networking
    path: "./patches/set-traefik-helmrelease-entries.yaml"
