---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: redis
  namespace: redis

spec:
  interval: 1h

  chartRef:
    kind: OCIRepository
    name: bitnami-redis
    namespace: flux-system

  values:
    architecture: standalone
