---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer

metadata:
  name: letsencrypt

spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: letsencrypt@mantannest.com

    privateKeySecretRef:
      name: letsencrypt

    solvers:
      - dns01:
          cloudflare:
            email: cloudflare@ahmedmasood.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "mantannest.com"
