---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: cert-manager
  namespace: networking

spec:
  interval: 1h

  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      version: v1.18.2

  releaseName: cert-manager
  targetNamespace: networking

  values:
    crds:
      enabled: true
    replicaCount: 1
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
