# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  interval: 1h
  chart:
    spec:
      chart: democratic-csi
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      version: 0.14.7
  releaseName: democratic-csi
  targetNamespace: democratic-csi
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      driver:
        enabled: true
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
    driver:
      config:
        driver: freenas-api-nfs
        httpConnection:
          protocol: https
          apiKey: ENC[AES256_GCM,data:eBEjWk+v1q8KrgSKZ0z/ntV0eACSN2SW95V7IeXNWZtO9l2rkEtGjZ4AgvksASmX9RYfcEYvhom6Y+yYzNTZyXT9,iv:nRNYt8+nT2kwafNi4CBsIVMu+88Ti+V610c8uU0JJE8=,tag:57i+DCSLhR91FXh3VGmbBA==,type:str]
          host: nas-server.local.mantannest.com
          port: 443
          allowInsecure: false
        zfs:
          datasetParentName: DataStore/k8s/nfs/volumes
          detachedSnapshotsDatasetParentName: DataStore/k8s/nfs/snapshots
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareCommentTemplate: '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}'
          shareHost: nas-server.local.mantannest.com
          shareAlldirs: false
          shareAllowedHosts:
            - 10.0.20.111
            - 10.0.20.112
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
    csiDriver:
      # should be globally unique for a given cluster
      name: org.democratic-csi.freenas-api-nfs
    storageClasses:
      - name: truenas-nfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - nfsvers=4
    volumeSnapshotClasses:
      - name: truenas-nfs
sops:
  age:
    - recipient: age1s90xwvtqw9at892s8tyde9lp8vu3rs2lde7pwh7hayuc2sahmv6qmkwpff
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NTZQc1IybHcyYlVXME1w
        UGFKSzdNNk9iT2xhQ2Q0RklRS21TeTd1M0ZNCnV2ZHpFNUE2eVN3b2dLb2E1a1BL
        OHZwSXFYMS9JRWZ2WXRXaFRjcjFadmMKLS0tICtpVkFTUEVSS0YrbGIvWXVneFlp
        bmlWU3VKZWFEUG5qSnorL3J6Q3hBRTgKqf7VLyAgMo2aeH6zXcsj9wTD/93NEshB
        UYXOMWp4fg87TDja74epQlVXKzQxjqo3giVJajk4ogFQV5CKPmgD5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-28T02:14:35Z"
  mac: ENC[AES256_GCM,data:cY8sBufSoR91H6OL1LjZMt2zTR1aMz5/rPQ27/8dohOzCyhBsklNGJQWQo3vpjDR7j8uB8VqC+l63udKYdugt/azvXxQFTnPXBivQAUw8QPGOQCGtVbBgMZdANM4s+GwnN1O/vOJdRU02Edvp1zQhjljhpqgJxCpxpcEM7yJkfU=,iv:1h1uokSSJt1qcllpMRBkYjtdKwClwhKYLVXi5XZxeUA=,tag:+XsopjyoPT2zwBbPTEp/qQ==,type:str]
  encrypted_regex: (apiKey)
  mac_only_encrypted: true
  version: 3.10.2
