---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../base/cert-manager/"
  - "../base/cnpg/"
  - "../base/flux/"
  - "../base/monitoring/"
  - "../base/traefik/"

patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: cnpg-cluster
      namespace: cnpg
    path: "./patches/cnpg-cluster-values.yaml"
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: grafana-certificate
      namespace: monitoring
    path: "./patches/grafana-certificate-values.yaml"
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: grafana
      namespace: monitoring
    path: "./patches/grafana-ingress-values.yaml"
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
    path: "./patches/kube-prometheus-stack-helm-values.yaml"
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: traefik-dashboard-certificate
      namespace: traefik
    path: "./patches/traefik-dashboard-certificate-values.yaml"
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: traefik-dashboard
      namespace: traefik
    path: "./patches/traefik-dashboard-ingress-values.yaml"
