---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: infra-controllers
  namespace: flux-system

spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/homelab-staging/
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  prune: true
  wait: true


---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: infra-configs
  namespace: flux-system

spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs/homelab-staging/
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  prune: true
