---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../secrets/homelab-staging/cf-token.enc.yaml"
  - "../../secrets/homelab-staging/traefik-dashboard-auth.enc.yaml"
  - "../base/kube-system/"
  - "../base/networking/"
