---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../base/metallb-system/metallb/"
  - "../../secrets/homelab-staging/cf-token.enc.yaml"
  - "../base/cert-manager/"
  - "../base/traefik/"
