---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert

metadata:
  name: github-status
  namespace: flux-system

spec:
  providerRef:
    name: github-status
  eventSources:
    - kind: Kustomization
      name: "*"


---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider

metadata:
  name: github-status
  namespace: flux-system

spec:
  type: github
  address: https://github.com/masood09/infra-tofu
  secretRef:
    name: github-alert-api-token
