---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert

metadata:
  name: github-status
  namespace: flux-system

spec:
  providerRef:
    name: github-status
  eventSources:
    - kind: Kustomization
      name: "*"


---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider

metadata:
  name: github-status
  namespace: flux-system

spec:
  type: github
  address: https://github.com/masood09/infra-flux
  secretRef:
    name: github-alert-api-token


---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'



---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: flux-discord-webhook
