---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../secrets/homelab-staging/discord-webhook.enc.yaml"
  - "../base/flux/alert-discord/"
  - "../../secrets/homelab-staging/githubtoken.enc.yaml"
  - "../base/flux/alert-github/"
  - "../base/metallb-system/metallb/"
  - "../base/traefik/"
  - "../base/cert-manager/"
  # - "../base/democratic-csi/"
