---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: csi-driver-nfs
  namespace: kube-system

spec:
  interval: 1h

  chart:
    spec:
      chart: csi-driver-nfs
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
      version: 4.11.0

  releaseName: csi-driver-nfs
  targetNamespace: kube-system

  values:
    externalSnapshotter:
      enabled: true
