---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease

metadata:
  name: prometheus
  namespace: monitoring

spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 75.15.2
  interval: 1h

  values:
    fullnameOverride: prometheus # changed

    alertmanager:
      alertmanagerSpec: # changed
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-nonbackedup-csi
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi

    grafana:
      defaultDashboardsTimezone: "America/Toronto" # changed
      persistence: # changed
        enabled: true
        type: pvc
        storageClassName: nfs-nonbackedup-csi
        accessModes: ["ReadWriteOnce"]
        size: 10Gi

    kube-state-metrics:
      prometheus:
        monitor:
          relabelings: # changed
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node

    kubeEtcd:
      endpoints: # changed
        - 10.0.20.111

    kubelet:
      serviceMonitor: # changed
        metricRelabelings:
          - action: replace
            sourceLabels:
              - node
            targetLabel: instance

    kubeScheduler:
      endpoints: # changed
        - 10.0.20.111

    prometheus:
      prometheusSpec:
        replicaExternalLabelName: "replica" # changed
        ruleSelectorNilUsesHelmValues: false # changed
        serviceMonitorSelectorNilUsesHelmValues: false # changed
        podMonitorSelectorNilUsesHelmValues: false # changed
        probeSelectorNilUsesHelmValues: false # changed
        retention: 7d # changed
        enableAdminAPI: true # changed
        storageSpec: # changed
          volumeClaimTemplate:
            spec:
              storageClassName: nfs-nonbackedup-csi
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi

    prometheusOperator:
      prometheusConfigReloader: # changed
        resources:
          requests:
            cpu: 200m
            memory: 50Mi
          limits:
            memory: 100Mi

    prometheus-node-exporter:
      prometheus:
        monitor:
          enabled: true
          relabelings: # changed
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node
