---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik-external

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`grafana.staging.homelab.mantannest.com`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80

  tls:
    secretName: grafana-tls
