---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - "./HelmRepository.yaml"
  - "./HelmRelease.yaml"
  - "./ingress.yaml"

configMapGenerator:
  - name: kube-state-metrics-config
    files:
      - "./kube-state-metrics-config.yaml"
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: flux-grafana-dashboards
    files:
      - "./dashboards/control-plane.json"
      - "./dashboards/cluster.json"
      - "./dashboards/traefik.json"
      - "./dashboards/traefik-dash.json"
      - "./dashboards/cert-manager-overview.json"
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
        kustomize.toolkit.fluxcd.io/substitute: disabled

configurations:
  - kustomizeconfig.yaml
