---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: traefik
  namespace: networking
  labels:
    release: kube-prometheus-stack

spec:
  namespaceSelector:
    matchNames:
      - networking
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  endpoints:
    - targetPort: 9100
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
