---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer

metadata:
  name: letsencrypt-staging

spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: letsencrypt@mantannest.com

    privateKeySecretRef:
      name: letsencrypt-staging

    solvers:
      - dns01:
          cloudflare:
            email: cloudflare@ahmedmasood.com
            apiTokenSecretRef:
              name: cloudflare-token
              key: token
        selector:
          dnsZones:
            - "mantannest.com"
