apiVersion: v1
data:
  token: ENC[AES256_GCM,data:XFoWUmlz0pjzrNVcDaMO+3EGeqzWwjGsO5/qAGSJZaqfjWfoHMkL2NZ3EApsTJjTsj3VN8CLauxeBOWjotYIzWCiFoca012E3Y9aqBrKWOpVdArYRyhUxx3Zle1nO2O7/qIGyWKA49VsDb7jDg7Gz7n+cFoqj0GJaQfb3w==,iv:rR7fiz5VYAXX81TdG1j7UU3QmCEwZfQ+EC+iqK6K6Fk=,tag:I43pG1kNF6VuvxbPQ0o0pA==,type:str]
kind: Secret
metadata:
  name: github-alert-api-token
  namespace: flux-system
sops:
  age:
    - recipient: age1s90xwvtqw9at892s8tyde9lp8vu3rs2lde7pwh7hayuc2sahmv6qmkwpff
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcm40UUdmWnNNTlYxUlRH
        KzlMcjVCTHQ2Y2Q5UWlNSy9jQTc5UmdEVFY4Ckg2K1pRU3ZxNUZiNVJSUTJKZmFW
        a1duWnQ0K2tRTGpUREtIQkNrVDlCRUEKLS0tIExmTWU1YWJ5Rnltb3pqU3ZTb0tW
        V0NCWGxVbnZST3B2Y0grQjg0V2dCVjQKCUJycrtBtFGKfal3b5dqDK7TMEAqM2D7
        UrFjLJRu7jI+8nXgUXsrQFRzMrOSblU5wsx+ImZeAkm79uK5pjekfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-06T19:29:20Z"
  mac: ENC[AES256_GCM,data:rt4QbQiY3Tc6a/FtN5XaAz4exo528FD1wD95YGoJX5+xc6t0u1sj+/wRltZH+d1LR1ZErJfs/Mj+n+C1/2lomhOVf0LN7s075E6wLAi9Ezt11PMHx5KgZW9ALbw8kuSHmOcus78tj2NM87/0gNfRp4Mdw/N88uxwED3X3E29irk=,iv:2BfO64S5DFWOX/+Pk16nOcdzqjsbal2hJDT/eObiQAc=,tag:ywW44wwUzLuBV2S/4dUElA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
